### ISSUE TITLE
Fix Railway deployment failure caused by #1

### ISSUE THREAD

**Issue by johnboyes** [ProteusHK/ccf-ui#3]
Deployments to [Raillway][1] are failing after we merged #1.

Here's the relevant part of the Railway deployment logs:

<details>
<summary>Railway logs</summary>

```
src/boot/auth-header.ts(95,25): error TS2345: Argument of type '[string, string, ...any[]]' is not assignable to parameter of type '[method: string, url: string | URL, async: boolean, username?: string | null | undefined, password?: string | null | undefined]'.

  Target requires 3 element(s) but source may have fewer.
src/boot/auth-header.ts(113,28): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(117,47): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(117,69): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(118,27): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(125,48): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(125,70): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(128,11): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(136,26): error TS2322: Type 'Document | BodyInit | null | undefined' is not assignable to type 'Document | XMLHttpRequestBodyInit | null | undefined'.

  Type 'ReadableStream<any>' is not assignable to type 'Document | XMLHttpRequestBodyInit | null | undefined'.
src/boot/auth-header.ts(95,25): error TS2345: Argument of type '[string, string, ...any[]]' is not assignable to parameter of type '[method: string, url: string | URL, async: boolean, username?: string | null | undefined, password?: string | null | undefined]'.

  Target requires 3 element(s) but source may have fewer.
src/boot/auth-header.ts(113,28): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(117,47): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(117,69): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(118,27): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(125,48): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(125,70): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(128,11): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

src/boot/auth-header.ts(136,26): error TS2322: Type 'Document | BodyInit | null | undefined' is not assignable to type 'Document | XMLHttpRequestBodyInit | null | undefined'.

  Type 'ReadableStream<any>' is not assignable to type 'Document | XMLHttpRequestBodyInit | null | undefined'.
ERROR: "type-check" exited with 2.
```

</details>

[1]: https://railway.com

**Comment by johnboyes** [comment]
@coderabbitai nice work!  Just one problem: you forgot to give me the code! Please give me the full amended file (in a collapsible details section, as requested above).
